// Giz Livre — © 2026 Heraldo Antunes — Licença MIT (ver LICENSE)
import {text,line,rect,path,page,table,refTable} from './base.js';
const green='stroke="#1F6E43" stroke-width="3"';
const arrow=(x1,y1,x2,y2)=>{const a=Math.atan2(y2-y1,x2-x1),s=10;return line(x1,y1,x2,y2,green)+path(`M${x2-s*Math.cos(a-.45)} ${y2-s*Math.sin(a-.45)} L${x2} ${y2} L${x2-s*Math.cos(a+.45)} ${y2-s*Math.sin(a+.45)}`,green);};
const ANTIGOS = [
// Fontes primárias consultadas: https://math.nist.gov/DFTdata/atomdata/configuration.html ; https://physics.nist.gov/PhysRefData/Handbook/Tables/chromiumtable1.htm
{id:'esp-quimica-pauling',nome:'Pauling: diagrama diagonal e exceções',grupo:'quimica',make(){
 let b='';const xs=[105,235,365,495],ys=n=>205+(n-1)*59;['s · 2','p · 6','d · 10','f · 14'].forEach((s,i)=>b+=text(xs[i],164,s,26,'fill="#1F6E43"'));
 const cells=[];for(let n=1;n<=7;n++)for(let l=0;l<Math.min(n,4);l++)if(n+l<=8)cells.push({n,l,x:xs[l],y:ys(n)});
 for(let d=1;d<=8;d++){const c=cells.filter(a=>a.n+a.l===d).sort((a,b)=>a.n-b.n);if(c.length>1)b+=arrow(c[0].x+45,c[0].y-22,c.at(-1).x-45,c.at(-1).y+22);}
 for(const c of cells)b+=rect(c.x-36,c.y-21,72,42,'rx="8" fill="#fff" stroke="#1F6E43"')+text(c.x,c.y,c.n+'spdf'[c.l],28,'font-weight="600"');
 b+=line(580,150,580,605,'stroke="#d4ded7"')+text(780,166,'Ordem de preenchimento',28,'font-weight="600"');
 ['1s → 2s → 2p → 3s','3p → 4s → 3d → 4p','5s → 4d → 5p → 6s','4f → 5d → 6p → 7s','5f → 6d → 7p'].forEach((s,i)=>b+=text(780,225+i*54,s));
 b+=text(780,513,'Capacidades: 2, 6, 10 e 14 e⁻')+text(780,560,'Cr: [Ar] 3d⁵ 4s¹')+text(780,599,'Cu: [Ar] 3d¹⁰ 4s¹');
 return page('Distribuição eletrônica — regra de Pauling','Setas diagonais: menor n + ℓ; no empate, menor n primeiro.',b,{footer:'Regra aproximada: configurações reais admitem exceções (Cr e Cu).'});
}},
// Fonte primária consultada: https://goldbook.iupac.org/terms/view/I03158
{id:'esp-quimica-ions',nome:'Íons: cargas e eletroneutralidade',grupo:'quimica',make(){let b=table(['Cátions','Nome','Ânions','Nome'],[['Na⁺','sódio','Cl⁻','cloreto'],['K⁺','potássio','OH⁻','hidróxido'],['Ca²⁺','cálcio','CO₃²⁻','carbonato'],['Mg²⁺','magnésio','SO₄²⁻','sulfato'],['NH₄⁺','amônio','NO₃⁻','nitrato']],{rowH:57});b+=text(500,532,'A fórmula de um sal deve ter soma de cargas igual a zero.',28)+text(500,580,'Ca²⁺ + 2 Cl⁻ → CaCl₂     |     2 Na⁺ + SO₄²⁻ → Na₂SO₄',28);return page('Íons frequentes em água e laboratório','A carga pertence ao íon; o índice conta átomos ou grupos.',b,{footer:'Dissolver um sal pode produzir íons; a solução mantém eletroneutralidade.'});}},
// Fonte primária consultada: https://goldbook.iupac.org/terms/view/P04524
{id:'esp-quimica-ph',nome:'pH: escala e exemplos a 25 °C',grupo:'quimica',make(){let b=text(500,177,'pH = −log₁₀ a(H⁺)   ≈   −log₁₀([H⁺]/c°)',30)+text(500,220,'c° = 1 mol/L; aproximação para soluções diluídas.',26);for(let i=0;i<=14;i++){const x=50+i*60;b+=rect(x,255,60,66,`fill="${i===7?'#1F6E43':i%2?'#e5eee8':'#f2f6f3'}" stroke="#b9c8be"`)+text(x+30,288,i,28,i===7?'fill="#fff"':'');}b+=text(250,363,'Ácido: pH < 7',30)+text(500,363,'Neutro: pH = 7',30)+text(770,363,'Básico: pH > 7',30);b+=table(['Exemplo idealizado','Concentração (mol/L)','pH'],[['Ácido forte diluído','[H⁺] = 10⁻³','3'],['Água pura a 25 °C','[H⁺] ≈ 10⁻⁷','≈ 7'],['Base forte diluída','[OH⁻] = 10⁻³','≈ 11']],{y:411,rowH:49,colWidths:[1.3,1.3,.5]});return page('pH em água — referência a 25 °C','Atividade é adimensional; a concentração é uma aproximação.',b,{footer:'pKw ≈ 14 a 25 °C. A neutralidade varia com T; pH pode sair de 0–14.'});}},
// Fonte primária consultada: https://edu.rsc.org/experiments/displacement-reactions-between-metals-and-their-salts/720.article
{id:'esp-quimica-reatividade',nome:'Reatividade: deslocamento entre metais',grupo:'quimica',make(){let b=text(500,174,'Ordem qualitativa para os quatro metais comparados',28);const names=['Mg','Zn','Fe','Cu'];names.forEach((s,i)=>{const x=85+i*235;b+=rect(x,232,155,94,'rx="12" fill="#eef5f0" stroke="#1F6E43"')+text(x+77.5,279,s,38,'font-weight="700"');if(i<3)b+=arrow(x+165,279,x+217,279);});b+=text(500,365,'Maior tendência a oxidar → menor tendência a oxidar',28)+line(50,407,950,407,'stroke="#d4ded7"')+text(500,454,'Zn(s) + Cu²⁺(aq) → Zn²⁺(aq) + Cu(s)',32,'fill="#1F6E43"')+text(500,508,'O zinco perde elétrons; o cobre(II) recebe elétrons.',28)+text(500,563,'A reação inversa não é espontânea nas mesmas condições.',26);return page('Série de reatividade — recorte experimental','Comparação de Mg, Zn, Fe e Cu em soluções de seus sais.',b,{footer:'Concentração, temperatura, passivação e cinética influenciam o observado.'});}},
// Fonte primária consultada: https://www.old.goldbook.iupac.org/html/S/S05742.html
{id:'esp-quimica-solubilidade',nome:'Solubilidade: produto iônico e condições',grupo:'quimica',make(){let b=text(500,174,'AgCl(s) ⇌ Ag⁺(aq) + Cl⁻(aq)',32,'fill="#1F6E43"')+text(500,223,'Kₚₛ(T) = a(Ag⁺) · a(Cl⁻)    |    Q = produto das atividades',28);[['Q < Kₚₛ','Insaturada','Sólido pode dissolver'],['Q = Kₚₛ','Saturada','Equilíbrio com sólido'],['Q > Kₚₛ','Supersaturada','Precipitação favorecida']].forEach((a,i)=>{const x=40+i*320;b+=rect(x,285,290,150,'rx="10" fill="#f1f6f2" stroke="#1F6E43"')+text(x+145,316,a[0],30,'font-weight="600"')+text(x+145,365,a[1],27)+text(x+145,410,a[2],26);});b+=table(['Condição','Por que importa?'],[['Temperatura e solvente','Mudam o equilíbrio de solubilidade'],['pH / complexação / íon comum','Mudam as espécies e suas atividades']],{y:469,rowH:46,colWidths:[1,1.5]});return page('Solubilidade — uma decisão condicionada','Kₚₛ vale para o sólido, as espécies e a temperatura especificados.',b,{footer:'Q > Kₚₛ indica tendência; nucleação e cinética podem retardar precipitação.'});}},
// Fonte primária consultada: https://goldbook.iupac.org/terms/view/F02555/PDF
{id:'esp-quimica-funcoes',nome:'Funções orgânicas: grupos característicos',grupo:'quimica',make(){const data=[['Álcool','R—OH','Hidroxila em C saturado'],['Éter','R—O—R′','Oxigênio entre carbonos'],['Aldeído','R—C(=O)—H','Carbonila terminal'],['Cetona','R—C(=O)—R′','Carbonila entre carbonos'],['Ácido carboxílico','R—C(=O)—OH','Grupo carboxila'],['Éster','R—C(=O)—O—R′','Derivado de ácido'],['Amina primária','R—NH₂','Nitrogênio ligado a R']];return page('Funções orgânicas — reconhecer o grupo','R e R′ representam grupos orgânicos; podem ser diferentes.',table(['Função','Fórmula geral','Reconhecimento'],data,{rowH:56,colWidths:[1,1.25,1.7]}),{h:720,footer:'Recorte introdutório: uma molécula pode reunir várias funções.'});}}
];



// Material de consulta: seleção, agrupamento, tradução e desenho próprios; dados creditados por entrada.
export const CONSULTA = [
// Fontes consultadas: https://www.cambridgeinternational.org/Images/664563-2025-2027-syllabus.pdf ; https://goldbook.iupac.org/terms/view/S05912/plain ; https://goldbook.iupac.org/terms/view/S05917/plain
{"id":"esp-quimica-potenciais-metais-1","nome":"E°: metais alcalinos, alcalino-terrosos e estruturais","grupo":"quimica",make(){return refTable("Potenciais padrão de redução: metais (1/2), 25 °C",[{"label":"Par / espécie","weight":2.4},{"label":"Semirreação de redução","weight":6.2},{"label":"E° (V)","weight":0.8,"align":"end"}],[["Lítio","Li⁺ + e⁻ → Li(s)","−3,04"],["Potássio","K⁺ + e⁻ → K(s)","−2,92"],["Cálcio","Ca²⁺ + 2e⁻ → Ca(s)","−2,87"],["Sódio","Na⁺ + e⁻ → Na(s)","−2,71"],["Magnésio","Mg²⁺ + 2e⁻ → Mg(s)","−2,38"],["Alumínio","Al³⁺ + 3e⁻ → Al(s)","−1,66"],["Zinco","Zn²⁺ + 2e⁻ → Zn(s)","−0,76"],["Ferro(II)/ferro","Fe²⁺ + 2e⁻ → Fe(s)","−0,44"],["Cobalto(II)/cobalto","Co²⁺ + 2e⁻ → Co(s)","−0,28"],["Níquel(II)/níquel","Ni²⁺ + 2e⁻ → Ni(s)","−0,25"]],{"w":1100,"rowH":38,"fonte":"Fonte: Cambridge International, Chemistry 9701, 2025–2027, pp. 85–87; IUPAC (EPH).","notas":["25 °C; atividades unitárias; p° = 1 bar; referência: eletrodo padrão de hidrogênio (EPH).","Íons em água; (s) sólido, (l) líquido, (g) gás, (aq) dissolvido. Valores da consolidação citada."]});}},
// Fontes consultadas: https://www.cambridgeinternational.org/Images/664563-2025-2027-syllabus.pdf ; https://goldbook.iupac.org/terms/view/S05912/plain ; https://goldbook.iupac.org/terms/view/S05917/plain
{"id":"esp-quimica-potenciais-metais-2","nome":"E°: metais e pares em solução","grupo":"quimica",make(){return refTable("Potenciais padrão de redução: metais (2/2), 25 °C",[{"label":"Par / espécie","weight":2.4},{"label":"Semirreação de redução","weight":6.2},{"label":"E° (V)","weight":0.8,"align":"end"}],[["Manganês(II)/metal","Mn²⁺ + 2e⁻ → Mn(s)","−1,18"],["Cromo(III)/metal","Cr³⁺ + 3e⁻ → Cr(s)","−0,74"],["Cromo(III)/cromo(II)","Cr³⁺ + e⁻ → Cr²⁺","−0,41"],["Estanho(II)/metal","Sn²⁺ + 2e⁻ → Sn(s)","−0,14"],["Chumbo(II)/metal","Pb²⁺ + 2e⁻ → Pb(s)","−0,13"],["Cobre(II)/cobre(I)","Cu²⁺ + e⁻ → Cu⁺","+0,15"],["Cobre(II)/metal","Cu²⁺ + 2e⁻ → Cu(s)","+0,34"],["Cobre(I)/metal","Cu⁺ + e⁻ → Cu(s)","+0,52"],["Ferro(III)/ferro(II)","Fe³⁺ + e⁻ → Fe²⁺","+0,77"],["Prata(I)/prata","Ag⁺ + e⁻ → Ag(s)","+0,80"]],{"w":1100,"rowH":38,"fonte":"Fonte: Cambridge International, Chemistry 9701, 2025–2027, pp. 85–87; IUPAC (EPH).","notas":["25 °C; atividades unitárias; p° = 1 bar; referência: eletrodo padrão de hidrogênio (EPH).","Íons em água; (s) sólido, (l) líquido, (g) gás, (aq) dissolvido. Valores da consolidação citada."]});}},
// Fontes consultadas: https://www.cambridgeinternational.org/Images/664563-2025-2027-syllabus.pdf ; https://goldbook.iupac.org/terms/view/S05912/plain ; https://goldbook.iupac.org/terms/view/S05917/plain
{"id":"esp-quimica-potenciais-oxidantes","nome":"E°: halogênios, água, oxigênio e oxidantes","grupo":"quimica",make(){return refTable("Potenciais padrão de redução: água e oxidantes, 25 °C",[{"label":"Par / espécie","weight":2.4},{"label":"Semirreação de redução","weight":6.2},{"label":"E° (V)","weight":0.8,"align":"end"}],[["Água/hidrogênio","2H₂O(l) + 2e⁻ → H₂(g) + 2OH⁻","−0,83"],["Hidrogênio (EPH)","2H⁺ + 2e⁻ → H₂(g)","0,00"],["Oxigênio/hidróxido","O₂(g) + 2H₂O(l) + 4e⁻ → 4OH⁻","+0,40"],["Iodo/iodeto","I₂(s) + 2e⁻ → 2I⁻","+0,54"],["Hipoclorito/cloreto","ClO⁻ + H₂O(l) + 2e⁻ → Cl⁻ + 2OH⁻","+0,89"],["Oxigênio/água","O₂(g) + 4H⁺ + 4e⁻ → 2H₂O(l)","+1,23"],["Dióxido/Mn(II)","MnO₂(s) + 4H⁺ + 2e⁻ → Mn²⁺ + 2H₂O(l)","+1,23"],["Dicromato/Cr(III)","Cr₂O₇²⁻ + 14H⁺ + 6e⁻ → 2Cr³⁺ + 7H₂O(l)","+1,33"],["Cloro/cloreto","Cl₂(g) + 2e⁻ → 2Cl⁻","+1,36"],["Permanganato/Mn(II)","MnO₄⁻ + 8H⁺ + 5e⁻ → Mn²⁺ + 4H₂O(l)","+1,52"],["Peróxido/água","H₂O₂(aq) + 2H⁺ + 2e⁻ → 2H₂O(l)","+1,77"],["Flúor/fluoreto","F₂(g) + 2e⁻ → 2F⁻","+2,87"]],{"w":1100,"rowH":33,"fonte":"Fonte: Cambridge International, Chemistry 9701, 2025–2027, pp. 85–87; IUPAC (EPH).","notas":["25 °C; atividades unitárias; p° = 1 bar; referência: eletrodo padrão de hidrogênio (EPH).","Íons em água; (s) sólido, (l) líquido, (g) gás, (aq) dissolvido. Valores da consolidação citada."]});}},
// Fontes consultadas: https://openstax.org/books/chemistry-2e/pages/2-6-ionic-and-molecular-compounds
{"id":"esp-quimica-ions-referencia","nome":"Íons de referência: cátions, nomes, fórmulas e cargas","grupo":"quimica",make(){return refTable("Íons comuns: cátions",[{"label":"Nome","weight":2.35},{"label":"Fórmula","weight":1.1},{"label":"Carga","weight":0.65,"align":"end"},{"label":"Nome","weight":2.35},{"label":"Fórmula","weight":1.1},{"label":"Carga","weight":0.65,"align":"end"}],[["Hidrogênio","H⁺","+1","Alumínio","Al³⁺","+3"],["Hidrônio","H₃O⁺","+1","Prata(I)","Ag⁺","+1"],["Lítio","Li⁺","+1","Ferro(II)","Fe²⁺","+2"],["Sódio","Na⁺","+1","Ferro(III)","Fe³⁺","+3"],["Potássio","K⁺","+1","Cobre(I)","Cu⁺","+1"],["Amônio","NH₄⁺","+1","Cobre(II)","Cu²⁺","+2"],["Magnésio","Mg²⁺","+2","Manganês(II)","Mn²⁺","+2"],["Cálcio","Ca²⁺","+2","Cobalto(II)","Co²⁺","+2"],["Bário","Ba²⁺","+2","Níquel(II)","Ni²⁺","+2"],["Zinco","Zn²⁺","+2","Chumbo(II)","Pb²⁺","+2"]],{"w":1100,"rowH":38,"fonte":"Fonte: OpenStax, Chemistry 2e, §2.6, figura 2.29 e tabela 2.5.","notas":["Fórmulas usuais: H⁺ representa próton solvatado. A carga é expressa em unidades de carga elementar."]});}},
// Fontes consultadas: https://openstax.org/books/chemistry-2e/pages/2-6-ionic-and-molecular-compounds ; https://www.cambridgeinternational.org/Images/664563-2025-2027-syllabus.pdf
{"id":"esp-quimica-ions-referencia-anions","nome":"Íons de referência: ânions, nomes, fórmulas e cargas","grupo":"quimica",make(){return refTable("Íons comuns: ânions",[{"label":"Nome","weight":2.35},{"label":"Fórmula","weight":1.1},{"label":"Carga","weight":0.65,"align":"end"},{"label":"Nome","weight":2.35},{"label":"Fórmula","weight":1.1},{"label":"Carga","weight":0.65,"align":"end"}],[["Fluoreto","F⁻","−1","Hidrogenossulfato","HSO₄⁻","−1"],["Cloreto","Cl⁻","−1","Sulfato","SO₄²⁻","−2"],["Brometo","Br⁻","−1","Di-hidrogenofosfato","H₂PO₄⁻","−1"],["Iodeto","I⁻","−1","Hidrogenofosfato","HPO₄²⁻","−2"],["Hidróxido","OH⁻","−1","Fosfato","PO₄³⁻","−3"],["Cianeto","CN⁻","−1","Hipoclorito","ClO⁻","−1"],["Azida","N₃⁻","−1","Clorito","ClO₂⁻","−1"],["Acetato","CH₃COO⁻","−1","Clorato","ClO₃⁻","−1"],["Nitrito","NO₂⁻","−1","Perclorato","ClO₄⁻","−1"],["Nitrato","NO₃⁻","−1","Permanganato","MnO₄⁻","−1"],["Hidrogenocarbonato","HCO₃⁻","−1","Cromato","CrO₄²⁻","−2"],["Carbonato","CO₃²⁻","−2","Dicromato","Cr₂O₇²⁻","−2"],["Hidrogenossulfito","HSO₃⁻","−1","Peróxido","O₂²⁻","−2"],["Sulfito","SO₃²⁻","−2","Tiossulfato","S₂O₃²⁻","−2"]],{"w":1100,"rowH":32,"fonte":"Fontes: OpenStax, Chemistry 2e, §2.6; Cambridge International, Chemistry 9701, p. 70."});}},
// Fontes consultadas: https://openstax.org/books/chemistry-2e/pages/h-ionization-constants-of-weak-acids
{"id":"esp-quimica-ka-pka-comuns","nome":"Ka e pKa a 25 °C: ácidos comuns","grupo":"quimica",make(){return refTable("Constantes ácido-base em água: ácidos comuns, 25 °C",[{"label":"Ácido / sistema","weight":2.65},{"label":"Espécie ácida","weight":1.8},{"label":"Etapa","weight":0.7,"align":"end"},{"label":"Ka","weight":1.65,"align":"end"},{"label":"pKa","weight":0.8,"align":"end"}],[["Acético","CH₃COOH","1","1,8 × 10⁻⁵","4,74"],["Fórmico","HCOOH","1","1,8 × 10⁻⁴","3,74"],["Fluorídrico","HF","1","6,4 × 10⁻⁴","3,19"],["Cianídrico","HCN","1","4,9 × 10⁻¹⁰","9,31"],["Nitroso","HNO₂","1","4,6 × 10⁻⁴","3,34"],["Hipocloroso","HClO","1","2,9 × 10⁻⁸","7,54"],["Hipobromoso","HBrO","1","2,8 × 10⁻⁹","8,55"],["Peróxido de hidrogênio","H₂O₂","1","2,4 × 10⁻¹²","11,62"],["Bórico¹","B(OH)₃","1","5,4 × 10⁻¹⁰","9,27"]],{"w":1100,"rowH":38,"fonte":"Fonte: OpenStax, Chemistry 2e, apêndice H. pKa = −log₁₀ Ka, calculado com duas casas.","notas":["Força iônica não informada pela fonte. Constantes de referência; não corrigidas para uma amostra.","¹ B(OH)₃ + H₂O ⇌ B(OH)₄⁻ + H⁺; constante global de formação de borato."]});}},
// Fontes consultadas: https://openstax.org/books/chemistry-2e/pages/h-ionization-constants-of-weak-acids ; https://water.usgs.gov/water-resources/memos/memo.php?id=2098 ; https://pubs.usgs.gov/wsp/1535c/report.pdf
{"id":"esp-quimica-ka-pka-etapas","nome":"Ka e pKa a 25 °C: etapas e sistema carbonato","grupo":"quimica",make(){return refTable("Constantes ácido-base em água: etapas, 25 °C",[{"label":"Ácido / sistema","weight":2.65},{"label":"Espécie ácida","weight":1.8},{"label":"Etapa","weight":0.7,"align":"end"},{"label":"Ka","weight":1.65,"align":"end"},{"label":"pKa","weight":0.8,"align":"end"}],[["Oxálico","H₂C₂O₄","1","6,0 × 10⁻²","1,22"],["Oxálico","HC₂O₄⁻","2","6,1 × 10⁻⁵","4,21"],["Fosfórico","H₃PO₄","1","7,5 × 10⁻³","2,12"],["Fosfórico","H₂PO₄⁻","2","6,2 × 10⁻⁸","7,21"],["Fosfórico","HPO₄²⁻","3","4,2 × 10⁻¹³","12,38"],["Fosforoso","H₃PO₃","1","5 × 10⁻²","1,30"],["Fosforoso","H₂PO₃⁻","2","2,0 × 10⁻⁷","6,70"],["Sulfúrico (2ª etapa)","HSO₄⁻","2","1,2 × 10⁻²","1,92"],["Carbonato²","CO₂*","1","4,5 × 10⁻⁷","6,35"],["Carbonato²","HCO₃⁻","2","4,7 × 10⁻¹¹","10,33"]],{"w":1100,"rowH":36,"fonte":"Fontes: OpenStax, Chemistry 2e, apêndice H; USGS, OWQ 2012.05, apêndice.","notas":["OpenStax: força iônica não indicada. USGS (carbonato): água doce diluída, diluição infinita.","² CO₂* = CO₂(aq) + H₂CO₃(aq); Ka₁ aparente. pKa = −log₁₀ Ka; Ka do carbonato com 2 algarismos."]});}},
];
export default [...ANTIGOS,...CONSULTA];
